import "./style.css";
const Anxiety = () => {

  return (
    <div>
      <div className="banner-area-anxiet">
        <h1>Anxiety</h1>
        <h3>and what it acutally is</h3>
      </div>
      <div className="content-wrapper">
        <h4 class="content-title">What is anxiety exactly</h4>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo, libero iure nesciunt excepturi cum unde, nostrum accusantium dolorem, quis aliquid ullam quas delectus incidunt assumenda ipsam. Error qui culpa ipsum nostrum minus corrupti quaerat, eos architecto modi quae magnam. Non, accusantium consectetur veritatis, ea nesciunt possimus magni et sapiente velit aut numquam officia laborum delectus fuga molestiae, voluptate repellat accusamus quod? Illum voluptatem praesentium quae culpa totam, labore numquam voluptatum sint doloribus, ullam consectetur itaque nulla, vero vitae nisi deserunt doloremque nesciunt dicta perspiciatis architecto? Totam, quis, ducimus voluptates earum architecto neque officia minima repellendus, maiores accusantium corrupti delectus odit laborum nesciunt fuga quo ad vel? Consequuntur cumque fugit voluptatibus natus alias sed fuga exercitationem in impedit. Voluptate iste vel quis aut, quas ad eos expedita unde quae veritatis hic cumque fugit corrupti ab quod amet? Dicta mollitia nisi voluptatum eligendi repellat, sequi dolor architecto explicabo, sit perspiciatis soluta distinctio.
        </p>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora laborum sint repellat, beatae assumenda consequuntur, voluptatibus ab temporibus unde nemo quo quibusdam labore amet dignissimos, quae reiciendis itaque! Labore eligendi iste ea vel sapiente ex eum, libero optio consequuntur cupiditate consequatur commodi impedit, rerum placeat ipsam quibusdam minima. Molestias praesentium, odit nisi officiis eum id molestiae harum vero. Esse consequuntur libero, saepe neque mollitia cum adipisci molestiae voluptatum iste, sunt ullam reprehenderit ratione dolorum, atque aliquid! Placeat officiis, ratione fugit ab sunt quae maiores mollitia vero, aliquam eos harum iusto laborum architecto nam accusamus fuga impedit. Et vitae blanditiis praesentium corporis animi, laudantium ducimus possimus alias quaerat tempore quidem iste explicabo quibusdam quo accusantium expedita non dolor. A, fugit neque nemo quia corporis cumque perspiciatis, ratione facere numquam aliquid excepturi perferendis inventore sapiente! Aliquam iure nihil corporis at dolorum, blanditiis ipsa aperiam cumque eligendi explicabo. Repellat corporis quod assumenda enim odio vero, error illo unde quibusdam aspernatur quo reprehenderit impedit distinctio. Atque obcaecati ducimus eaque, delectus similique dicta quam consectetur possimus quisquam error aliquam esse, eveniet dignissimos quae animi quaerat expedita laboriosam perspiciatis vero! Hic asperiores fugiat veniam aliquid doloremque! Aperiam enim in ad sed dolore doloribus ratione fugit eligendi quae. Officiis enim facere quasi molestias illo natus sint. Dolorem modi assumenda, adipisci eligendi non animi cum, in enim deserunt ullam amet! Sapiente ipsa laborum similique autem officiis, sequi delectus corporis maiores, quas neque aperiam qui itaque eius molestias at facere ipsam, ratione quibusdam natus velit veniam est modi reiciendis fugit? Voluptatibus quia perspiciatis necessitatibus eos tempora odit sed tempore saepe, libero temporibus! Eaque dolorum doloribus nisi, voluptatibus doloremque fugiat iure blanditiis placeat sunt excepturi praesentium harum provident dolores tenetur sequi perspiciatis ut. Possimus id ex provident quos expedita animi omnis aliquam earum cumque? Obcaecati ullam autem alias quo in.
        </p>

        <h4 class="content-title">What can you do when you have Anxiety</h4>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora laborum sint repellat, beatae assumenda consequuntur, voluptatibus ab temporibus unde nemo quo quibusdam labore amet dignissimos, quae reiciendis itaque! Labore eligendi iste ea vel sapiente ex eum, libero optio consequuntur cupiditate consequatur commodi impedit, rerum placeat ipsam quibusdam minima. Molestias praesentium, odit nisi officiis eum id molestiae harum vero. Esse consequuntur libero, saepe neque mollitia cum adipisci molestiae voluptatum iste, sunt ullam reprehenderit ratione dolorum, atque aliquid! Placeat officiis, ratione fugit ab sunt quae maiores mollitia vero, aliquam eos harum iusto laborum architecto nam accusamus fuga impedit. Et vitae blanditiis praesentium corporis animi, laudantium ducimus possimus alias quaerat tempore quidem iste explicabo quibusdam quo accusantium expedita non dolor. A, fugit neque nemo quia corporis cumque perspiciatis, ratione facere numquam aliquid excepturi perferendis inventore sapiente! Aliquam iure nihil corporis at dolorum, blanditiis ipsa aperiam cumque eligendi explicabo. Repellat corporis quod assumenda enim odio vero, error illo unde quibusdam aspernatur quo reprehenderit impedit distinctio. Atque obcaecati ducimus eaque, delectus similique dicta quam consectetur possimus quisquam error aliquam esse, eveniet dignissimos quae animi quaerat expedita laboriosam perspiciatis vero! Hic asperiores fugiat veniam aliquid doloremque! Aperiam enim in ad sed dolore doloribus ratione fugit eligendi quae. Officiis enim facere quasi molestias illo natus sint. Dolorem modi assumenda, adipisci eligendi non animi cum, in enim deserunt ullam amet! Sapiente ipsa laborum similique autem officiis, sequi delectus corporis maiores, quas neque aperiam qui itaque eius molestias at facere ipsam, ratione quibusdam natus velit veniam est modi reiciendis fugit? Voluptatibus quia perspiciatis necessitatibus eos tempora odit sed tempore saepe, libero temporibus! Eaque dolorum doloribus nisi, voluptatibus doloremque fugiat iure blanditiis placeat sunt excepturi praesentium harum provident dolores tenetur sequi perspiciatis ut. Possimus id ex provident quos expedita animi omnis aliquam earum cumque? Obcaecati ullam autem alias quo in.
        </p>
        <h4 class="content-title">What can you do when someone you know has Anxiety</h4>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora laborum sint repellat, beatae assumenda consequuntur, voluptatibus ab temporibus unde nemo quo quibusdam labore amet dignissimos, quae reiciendis itaque! Labore eligendi iste ea vel sapiente ex eum, libero optio consequuntur cupiditate consequatur commodi impedit, rerum placeat ipsam quibusdam minima. Molestias praesentium, odit nisi officiis eum id molestiae harum vero. Esse consequuntur libero, saepe neque mollitia cum adipisci molestiae voluptatum iste, sunt ullam reprehenderit ratione dolorum, atque aliquid! Placeat officiis, ratione fugit ab sunt quae maiores mollitia vero, aliquam eos harum iusto laborum architecto nam accusamus fuga impedit. Et vitae blanditiis praesentium corporis animi, laudantium ducimus possimus alias quaerat tempore quidem iste explicabo quibusdam quo accusantium expedita non dolor. A, fugit neque nemo quia corporis cumque perspiciatis, ratione facere numquam aliquid excepturi perferendis inventore sapiente! Aliquam iure nihil corporis at dolorum, blanditiis ipsa aperiam cumque eligendi explicabo. Repellat corporis quod assumenda enim odio vero, error illo unde quibusdam aspernatur quo reprehenderit impedit distinctio. Atque obcaecati ducimus eaque, delectus similique dicta quam consectetur possimus quisquam error aliquam esse, eveniet dignissimos quae animi quaerat expedita laboriosam perspiciatis vero! Hic asperiores fugiat veniam aliquid doloremque! Aperiam enim in ad sed dolore doloribus ratione fugit eligendi quae. Officiis enim facere quasi molestias illo natus sint. Dolorem modi assumenda, adipisci eligendi non animi cum, in enim deserunt ullam amet! Sapiente ipsa laborum similique autem officiis, sequi delectus corporis maiores, quas neque aperiam qui itaque eius molestias at facere ipsam, ratione quibusdam natus velit veniam est modi reiciendis fugit? Voluptatibus quia perspiciatis necessitatibus eos tempora odit sed tempore saepe, libero temporibus! Eaque dolorum doloribus nisi, voluptatibus doloremque fugiat iure blanditiis placeat sunt excepturi praesentium harum provident dolores tenetur sequi perspiciatis ut. Possimus id ex provident quos expedita animi omnis aliquam earum cumque? Obcaecati ullam autem alias quo in.
        </p>
        <h4 class="content-title">Seek Help Here</h4>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora laborum sint repellat, beatae assumenda consequuntur, voluptatibus ab temporibus unde nemo quo quibusdam labore amet dignissimos, quae reiciendis itaque! Labore eligendi iste ea vel sapiente ex eum, libero optio consequuntur cupiditate consequatur commodi impedit, rerum placeat ipsam quibusdam minima. Molestias praesentium, odit nisi officiis eum id molestiae harum vero. Esse consequuntur libero, saepe neque mollitia cum adipisci molestiae voluptatum iste, sunt ullam reprehenderit ratione dolorum, atque aliquid! Placeat officiis, ratione fugit ab sunt quae maiores mollitia vero, aliquam eos harum iusto laborum architecto nam accusamus fuga impedit. Et vitae blanditiis praesentium corporis animi, laudantium ducimus possimus alias quaerat tempore quidem iste explicabo quibusdam quo accusantium expedita non dolor. A, fugit neque nemo quia corporis cumque perspiciatis, ratione facere numquam aliquid excepturi perferendis inventore sapiente! Aliquam iure nihil corporis at dolorum, blanditiis ipsa aperiam cumque eligendi explicabo. Repellat corporis quod assumenda enim odio vero, error illo unde quibusdam aspernatur quo reprehenderit impedit distinctio. Atque obcaecati ducimus eaque, delectus similique dicta quam consectetur possimus quisquam error aliquam esse, eveniet dignissimos quae animi quaerat expedita laboriosam perspiciatis vero! Hic asperiores fugiat veniam aliquid doloremque! Aperiam enim in ad sed dolore doloribus ratione fugit eligendi quae. Officiis enim facere quasi molestias illo natus sint. Dolorem modi assumenda, adipisci eligendi non animi cum, in enim deserunt ullam amet! Sapiente ipsa laborum similique autem officiis, sequi delectus corporis maiores, quas neque aperiam qui itaque eius molestias at facere ipsam, ratione quibusdam natus velit veniam est modi reiciendis fugit? Voluptatibus quia perspiciatis necessitatibus eos tempora odit sed tempore saepe, libero temporibus! Eaque dolorum doloribus nisi, voluptatibus doloremque fugiat iure blanditiis placeat sunt excepturi praesentium harum provident dolores tenetur sequi perspiciatis ut. Possimus id ex provident quos expedita animi omnis aliquam earum cumque? Obcaecati ullam autem alias quo in.
        </p>
      </div>
    </div >

  );
};

export default Anxiety;